import Head from 'next/head'
import Image from 'next/image'
import localFont from '@next/font/local'
import styles from '../styles/Home.module.scss'

const myFont = localFont({ src: './fonts/NewYork.otf' })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Image className={styles.bgImage} src='/images/sao-vicente.jpg' alt={''} fill/>
      <main>
        <h1 className={`${myFont.className} ${styles.h1}`}>Calendário Litúrgico</h1>
        <h3>PARÓQUIA SÃO VICENTE DE PAULO - NOVA ANDRADINA/MS</h3>
      </main>
    </>
  )
}
